name: Lint

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: raven-actions/actionlint@v2
        with:
          files: ".github/workflows/*.yaml .github/actions/*/action.yml"
